### ISSUE TITLE
[Feature request]  Get the mismatched fields, missing fields as objects for custom usage

### ISSUE THREAD

**Issue by aymar99** [deblockt/json-diff#15]
The OnlyErrorDiffViewer provides all the mismatch details between the expected and actual json as string in certain format. As a end user, i may want it in a different format than what's provided. Is it possible to expose a method that can fetch all the details displayed as an object so that it can be used as per our use case.

If something close to the below is returned it would be useful,
The mismatched errors could be a list of object, each object can have 3 string data members - path, expectedVal, actualVal
The not found in expected errors could be a list of string paths
The not found in actual errors could be a list of string paths

**Comment by deblockt** [comment]
I can add a class to provide a object view of the diff. This object will contains for each json path the actual value and the expected value. 
But in the philosophy of this library, if you need to display the diff in a way other than the one provided, you need to implement a custom [JsonDiffViewer](https://github.com/deblockt/json-diff/blob/master/src/main/java/com/deblock/jsondiff/viewer/JsonDiffViewer.java). The [JsonDiffViewer](https://github.com/deblockt/json-diff/blob/master/src/main/java/com/deblock/jsondiff/viewer/JsonDiffViewer.java) contains some method for each diff cases (missing property, matching property, extra properties, etc...). You can read the [OnlyErrorDiffViewer](https://github.com/deblockt/json-diff/blob/master/src/main/java/com/deblock/jsondiff/viewer/OnlyErrorDiffViewer.java) class to have an exemple. Do you think that can fit to your needs ?

**Comment by aymar99** [comment]
I didn't think of this approach, then this would suffice for my use case, thanks!
