### ISSUE TITLE
hard-coded 99.9 similarity causes issues

### ISSUE THREAD

**Issue by bvdeenen** [deblockt/json-diff#2]
I'm using json-diff to diff quite large files, and need a variation of the `OnlyErrorDiffViewer`. Having a text node value change caused *nothing* in the `OnlyErrorDiffViewer`. The `PatchDiffViewer` however showed that the change was detected.

Some sleuthing showed that the hard-coded `>= 99.9` in `JsonObjectDiff:display` is the culprit. Changing this to `== 100.0` fixed my issue (my diff gave a `similarityRate` of 99.97).

I think the 99.9 is wrong. For this kind of work, it should just be a simple `== 100.0`. There's no need to be careful with floating point comparisons, because two json strings that represent the same floating point value will always have the same in-memory representation. Any change whatsoever will cause the result to become different from 100.

Thanks for the library, with the patch it's very useful for us at strmprivacy.io for tracking changes in large documents.

**Comment by bvdeenen** [comment]
If you need, I can provide json files that show the issue.

**Comment by deblockt** [comment]
Hi, 

Happy to see that this lib can be useful :) 
I don't remember why I have use 99.9 instead of 100 :/ 
I will try to set it to 100 and check is that break some test.

**Comment by deblockt** [comment]
I juste released the 0.0.6 version how fix this issue.
