### ISSUE TITLE
Diff not detected

### ISSUE THREAD

**Issue by bvdeenen** [deblockt/json-diff#4]
```kotlin
            val org = """{"d":2}"""
            val new = """{"d":2, "e": {"f":"g"}}"""
            val matcher = CompositeJsonMatcher(
                LenientJsonArrayPartialMatcher(),
                LenientJsonObjectPartialMatcher(),
                StrictPrimitivePartialMatcher(),
            )
            val jsonDiff = DiffGenerator.diff(org, new, matcher)
            val patch = PatchDiffViewer.from(jsonDiff)

```
Neither the `PatchDiffViewer` nor the `OnlyErrorDiffViewer` detect any difference. I'm having a look to see if I can find the cause.

**Comment by bvdeenen** [comment]
Sleuthing in the codebase, I can see where it goes wrong. `LenientJsonObjectPartialMatcher:.jsonDiff` only looks from the `expectedJson` fields, but not the other way around. If I change the order of `org` and `new` there is a difference.

**Comment by deblockt** [comment]
Hi, 

Yes it's the expected behavior of lenient comparator. 
Strict comparators are not yet implemented.

**Comment by bvdeenen** [comment]
I'm working on it, will put together some code and tests in my forked codebase. Should be ready this weekend.

**Comment by bvdeenen** [comment]
I've got a workaround for the issue I'm facing, but the `PatchDiffViewer` gives the wrong output, so I'm not yet ready for the unit-tests. I just added
```java
        receivedJson.fields()
            .forEachRemaining(entry -> {
                final var receivedPropertyName = entry.getKey();
                final var receivedPropertyValue = entry.getValue();
                final var expectedValue = expectedJson.get(receivedPropertyName);

                if (expectedValue == null) {
                    final var diff = new JsonObjectDiff(path.add(Path.PathItem.of(receivedPropertyName)));
                    diff.addNotFoundProperty(receivedPropertyName, receivedPropertyValue);
                    jsonDiff.addPropertyDiff(receivedPropertyName, diff);
                }
            });

```
to the `LenientJsonObjectPartialMatcher.jsonDiff` method.

**Comment by deblockt** [comment]
Fill free to create a pull request, but you you create a new class and don't modify `LenientJsonObjectPartialMatcher` thanks

**Comment by bvdeenen** [comment]
I think I've got it covered but in another codebase; will create a pull request somewhere in the coming week.

**Comment by bvdeenen** [comment]
I've created a PR #7 to address this need.
